### PR TITLE
LAMMPS 29Oct2020 in 2020b

### PR DESCRIPTION
**Pull request by afraz-ahmed**
For ExCALIBUR and INC1129085 - `LAMMPS-29Oct2020-foss-2020b-kokkos.eb`

Please also see https://github.com/bear-rsg/easybuild-easyblocks/pull/85.

* [x] Assigned to reviewers (usually everyone in apps team)

Note: will not work with `srun`.

Default:
* [ ] EL8-cascadelake
* [ ] EL8-haswell

The `USER-SDPD` package has been added to `LAMMPS`.

`LAMMPS` gives `Eigen/3.3.8-GCCcore-10.2.0/include/Eigen/src/Core/products/Parallelizer.h:162:19: error: eigen_assert_exception is not a member of Eigen` when building with `Eigen/3.3.8-GCCcore-10.2.0`, so `Eigen 3.3.9` was used.

`ScaFaCoS` needs the addition of `configopts += 'FCFLAGS="$FCFLAGS -fallow-argument-mismatch" '` to work with `GCC 10`.

`yaff` doesn't build with `h5py/3.1.0-foss-2020b`, so `h5py 2.10.0` was used.

`LAMMPS-29Oct2020_VTK9.patch` is needed for `LAMMPS` to build with `VTK 9` (to avoid `LAMMPS/29Oct2020/foss-2020b-kokkos/lammps-stable_29Oct2020/src/USER-VTK/dump_vtk.cpp:1092:20: error: class vtkIntArray has no member named InsertNextTupleValue; did you mean InsertNextTuple?`). 

`VTK 8.2.0` has a different problem with `GCC 10`: `/binutils/2.35-GCCcore-10.2.0/bin/ld.gold: error: CMakeFiles/vtkexodusII.dir/src/ex_open_par.c.o: multiple definition of 'exodus_unused_symbol_dummy_1'`. This has been fixed in version 9.

### CODE REVIEW

**Review by rpep — APPROVED** [review]
all looks fine to me
